"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.debugRuntimeConfig = exports.onFollowCreate = exports.onCommentCreate = exports.onLikeCreate = exports.collectAPIMetrics = exports.collectCDNMetrics = exports.monitorStorageUsage = exports.warmCDNCache = exports.generateSignedUrl = exports.ensureAdminRole = exports.revokeAdminRole = exports.assignAdminRole = exports.cleanupRawVideos = exports.checkSystemAlerts = exports.calculateTrendingVideos = exports.aggregateVideoAnalytics = exports.aggregateUserAnalytics = exports.sendPushNotification = exports.aggregateAPIMetricsHourly = exports.systemHealthCheck = exports.flagVideo = exports.createVideoDraft = exports.retryProcessCaptions = exports.processCaptions = exports.retryProcessVideo = exports.processVideoUpload = void 0;
// Cloudinary credentials updated: 2025-11-14
// Force redeploy to apply new credentials
var processVideoUpload_1 = require("./video/processVideoUpload");
Object.defineProperty(exports, "processVideoUpload", { enumerable: true, get: function () { return processVideoUpload_1.processVideoUpload; } });
Object.defineProperty(exports, "retryProcessVideo", { enumerable: true, get: function () { return processVideoUpload_1.retryProcessVideo; } });
var processCaptions_1 = require("./video/processCaptions");
Object.defineProperty(exports, "processCaptions", { enumerable: true, get: function () { return processCaptions_1.processCaptions; } });
Object.defineProperty(exports, "retryProcessCaptions", { enumerable: true, get: function () { return processCaptions_1.retryProcessCaptions; } });
var createVideoDraft_1 = require("./video/createVideoDraft");
Object.defineProperty(exports, "createVideoDraft", { enumerable: true, get: function () { return createVideoDraft_1.createVideoDraft; } });
var flagVideo_1 = require("./video/flagVideo");
Object.defineProperty(exports, "flagVideo", { enumerable: true, get: function () { return flagVideo_1.flagVideo; } });
var systemHealthCheck_1 = require("./analytics/systemHealthCheck");
Object.defineProperty(exports, "systemHealthCheck", { enumerable: true, get: function () { return systemHealthCheck_1.systemHealthCheck; } });
var aggregateApiMetrics_1 = require("./analytics/aggregateApiMetrics");
Object.defineProperty(exports, "aggregateAPIMetricsHourly", { enumerable: true, get: function () { return aggregateApiMetrics_1.aggregateAPIMetricsHourly; } });
var sendNotifications_1 = require("./notifications/sendNotifications");
Object.defineProperty(exports, "sendPushNotification", { enumerable: true, get: function () { return sendNotifications_1.sendPushNotification; } });
var userAnalytics_1 = require("./analytics/userAnalytics");
Object.defineProperty(exports, "aggregateUserAnalytics", { enumerable: true, get: function () { return userAnalytics_1.aggregateUserAnalytics; } });
var videoAnalytics_1 = require("./analytics/videoAnalytics");
Object.defineProperty(exports, "aggregateVideoAnalytics", { enumerable: true, get: function () { return videoAnalytics_1.aggregateVideoAnalytics; } });
var trendingContent_1 = require("./analytics/trendingContent");
Object.defineProperty(exports, "calculateTrendingVideos", { enumerable: true, get: function () { return trendingContent_1.calculateTrendingVideos; } });
var alertsSystem_1 = require("./analytics/alertsSystem");
Object.defineProperty(exports, "checkSystemAlerts", { enumerable: true, get: function () { return alertsSystem_1.checkSystemAlerts; } });
var cleanupRawVideos_1 = require("./storage/cleanupRawVideos");
Object.defineProperty(exports, "cleanupRawVideos", { enumerable: true, get: function () { return cleanupRawVideos_1.cleanupRawVideos; } });
var assignAdminRole_1 = require("./auth/assignAdminRole");
Object.defineProperty(exports, "assignAdminRole", { enumerable: true, get: function () { return assignAdminRole_1.assignAdminRole; } });
var revokeAdminRole_1 = require("./auth/revokeAdminRole");
Object.defineProperty(exports, "revokeAdminRole", { enumerable: true, get: function () { return revokeAdminRole_1.revokeAdminRole; } });
var ensureAdminRole_1 = require("./auth/ensureAdminRole");
Object.defineProperty(exports, "ensureAdminRole", { enumerable: true, get: function () { return ensureAdminRole_1.ensureAdminRole; } });
var generateSignedUrl_1 = require("./storage/generateSignedUrl");
Object.defineProperty(exports, "generateSignedUrl", { enumerable: true, get: function () { return generateSignedUrl_1.generateSignedUrl; } });
var warmCDNCache_1 = require("./storage/warmCDNCache");
Object.defineProperty(exports, "warmCDNCache", { enumerable: true, get: function () { return warmCDNCache_1.warmCDNCache; } });
var monitorStorage_1 = require("./analytics/monitorStorage");
Object.defineProperty(exports, "monitorStorageUsage", { enumerable: true, get: function () { return monitorStorage_1.monitorStorageUsage; } });
Object.defineProperty(exports, "collectCDNMetrics", { enumerable: true, get: function () { return monitorStorage_1.collectCDNMetrics; } });
var apiMetrics_1 = require("./analytics/apiMetrics");
Object.defineProperty(exports, "collectAPIMetrics", { enumerable: true, get: function () { return apiMetrics_1.collectAPIMetrics; } });
var rateLimitTriggers_1 = require("./social/rateLimitTriggers");
Object.defineProperty(exports, "onLikeCreate", { enumerable: true, get: function () { return rateLimitTriggers_1.onLikeCreate; } });
Object.defineProperty(exports, "onCommentCreate", { enumerable: true, get: function () { return rateLimitTriggers_1.onCommentCreate; } });
Object.defineProperty(exports, "onFollowCreate", { enumerable: true, get: function () { return rateLimitTriggers_1.onFollowCreate; } });
var debugRuntimeConfig_1 = require("./utils/debugRuntimeConfig");
Object.defineProperty(exports, "debugRuntimeConfig", { enumerable: true, get: function () { return debugRuntimeConfig_1.debugRuntimeConfig; } });
//# sourceMappingURL=index.js.map